app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');
// используем только маршрут index, псевдоним name
Route::resource('/','IndexController',[
	'only' => 'index',
	'names' => ['index' => 'home']
]);


Route::resource('portfolios','PortfolioController',[
	'parameters' => [
		'portfolios' => 'alias'
	]
]);


Route::resource('articles','ArticlesController',[
	'parameters' => [
		'articles' => 'alias'
	]
]);

//Route::get('articles/cat/{cat_alias?}', ['uses' => 'ArticlesController@index', 'as' => 'articlesCat'])->where('cat_alias','[\w-]+');
Route::get('articles/cat/{cat_alias?}', ['uses' => 'ArticlesController@index', 'as' => 'articlesCat']);

Route::resource('comment','CommentController',[
	'only' => 'store'
]);

Route::match(['get','post'],'/contacts',['uses'=>'ContactsController@index','as'=>'contacts']);

// формируем список маршрутов для аутентификации
Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function (){
	Route::get('/',['uses' => 'Admin\IndexController@index','as' => 'adminIndex']);
	// Route::resource('/articles','Admin/ArticlesController ');
	Route::resource('/articles', 'Admin\ArticlesController',[
		'names' => [
			'store' => 'admin.articles.store',
			'index' => 'admin.articles.index',
			'create' => 'admin.articles.create',
			'destroy' => 'admin.articles.destroy',
			'update' => 'admin.articles.update',
			'show' => 'admin.articles.show',
			'edit' => 'admin.articles.edit',
		],
	]);
	Route::resource('/permissions', 'Admin\PermissionsController',[
		'names' => [
			'store' => 'admin.permissions.store',
			'index' => 'admin.permissions.index',
			'create' => 'admin.permissions.create',
			'destroy' => 'admin.permissions.destroy',
			'update' => 'admin.permissions.update',
			'show' => 'admin.permissions.show',
			'edit' => 'admin.permissions.edit',
		],
	]);
	Route::resource('/menus', 'Admin\MenusController',[
		'names' => [
			'store' => 'admin.menus.store',
			'index' => 'admin.menus.index',
			'create' => 'admin.menus.create',
			'destroy' => 'admin.menus.destroy',
			'update' => 'admin.menus.update',
			'show' => 'admin.menus.show',
			'edit' => 'admin.menus.edit',
		],
	]);
	Route::resource('/users', 'Admin\UsersController',[
		'names' => [
			'store' => 'admin.users.store',
			'index' => 'admin.users.index',
			'create' => 'admin.users.create',
			'destroy' => 'admin.users.destroy',
			'update' => 'admin.users.update',
			'show' => 'admin.users.show',
			'edit' => 'admin.users.edit',
		],
	]);
});

app/resources/views/bootstrap4/advantages.blade.php
@if($advantages)
	<div class="b-advantages">
		<div class="b-advantages__inner">
			<div class="row">
				@foreach($advantages as $advantage)
					<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<div class="b-advantages__item">
							<div class="b-advantages__icon">
								<a href="{{$advantage->link}}">
									<i class="fa fa-{{$advantage->icon}}"></i>
								</a>
							</div>
							<div class="b-advantages__text">
								<a href="{{$advantage->link}}">{{$advantage->text}}</a>
							</div>
						</div>
					</div>
				@endforeach
			</div>
		</div>
	</div>
@endif

app/resources/views/bootstrap4/article_content.blade.php
@if($article)
    <div class="b-content">
        <div class="row">
            <div class="col-lg-5 col-md-6 col-sm-5 col-xs-12">
                <div class="b-news-page__img">
                    <img class="img-responsive" src="{{asset(env('THEME'))}}/img/{{ ($article->img) ? $article->img->path : 'no-img.jpg' }}">
                </div>
            </div>
            <div class="col-lg-7 col-md-6 col-sm-7 col-xs-12">
                {!! $article->text !!}
                <div class="b-attr">
                    <p><b>Filter:</b><span>{{$article->category->title}}</span></p>
                    <p><b>Author:</b><span>{{$article->user->name}}</span></p>
                    <p><b>Date:</b><span>{{$article->created_at->format('D d. M - Y')}}</span></p>
                </div>
            </div>
        </div>
        @if(count($article->comments)>0)
            <div class="row">
                <div class="col-lg-12">
                    <div id="comments">
                        <div class="b-header2">
                            <h2 class="b-h2" id="comments-title">{{count($article->comments)}} {{Lang::choice('ru.comments',count($article->comments))}}</h2>
                            <div class="b-h2__sub">leave a reply</div>
                        </div>
                        <ol class="commentlist group">
                            @foreach($articleGroup as $k => $comments)
                                @if($k !== 0)
                                    @break
                                @endif
                                @include(env('THEME').'.comments',['comments' => $comments])
                            @endforeach
                        </ol>
                        @include(env('THEME').'.comment_form')
                    </div>
                </div>
            </div>
        @endif
        <!--nav aria-label="...">
            <ul class="pager">
                <li class="previous"><a href="news.html">Prev</a></li>
                <li class="next"><a href="#">Next</a></li>
            </ul>
        </nav-->
    </div>
@endif

app/resources/views/bootstrap4/articles_content.blade.php
<div class="row flex-row">
    @if($articles)
        @foreach($articles as $article)
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <div class="b-news">
                    <div class="b-news__img">
                        <a class="b-news__link b-news--no_img" href="{{route('articles.show',['alias' => $article->alias])}}">
                            <img class="img-responsive" src="{{asset(env('THEME'))}}/img/{{ ($article->img) ? $article->img->path : 'no-img.jpg' }}">
                        </a>
                    </div>
                    <div class="b-news__content">
                        <div class="b-news__name">{{$article->title}}</div>
                        <div class="b-news__anons">
                            {{$article->desc}}
                            <br>
                            <b>
                                Author:
                            </b>
                            <span>{{$article->user->name}}</span>
                            <br>
                            <b>
                                Category:
                            </b>
                            <a href="{{route('articlesCat',['cat_alias' => $article->category->alias])}}">{{$article->category->title}}</a>
                            <br>
                            <b>
                                {{count($article->comments)}} {{Lang::choice('ru.comments',count($article->comments))}}
                            </b>
                            {{--
                            <div class="b-filters">
                                <a class="b-filter" href="{{route('articlesCat',['cat_alias' => $article->category->alias])}}">{{$article->category->title}}</a>
                            </div>
                            --}}
                            <div class="b-date-block"><b>Date:</b><span>{{$article->created_at->format('d D. M - Y')}}</span></div>
                        </div>
                        <a class="b-news__more" href="{{route('articles.show',['alias' => $article->alias])}}">{{Lang::get('ru.read_more')}}</a>
                    </div>
                </div>
            </div>
        @endforeach
    @else
        <p>{{Lang::get('ru.articles_no')}}</p>
    @endif
</div>

{{--
<nav class="text-center">
    {{$articles->links()}}
</nav>
--}}

app/resources/views/bootstrap4/comment_form.blade.php
{{--
<div class="b-header3">
	<h3 class="b-h3" id="reply-title">Form<small><a href="#respond" rel="nofollow" style="display:none;" id="cancel-comment-reply-link">Cancel reply</a></small></h3>
</div>
<div id="respond">
	<form class="b-feedback m-b__15px" id="commentform">
		@if(!Auth::check())

		@endif
		<input id="comment_post_ID" type="hidden" name="comment_post_ID" value="{{$article->id}}">
		<input id="comment_post_ID" type="hidden" name="comment_parent" value="">
		<div class="input-group">
			<span class="input-group-addon min-width__40px">
				<i class="fa fa-user"></i>
			</span>
			<input id="author" class="form-control" placeholder="Имя" name="author">
		</div>
		<div class="input-group">
			<span class="input-group-addon min-width__40px">
			<i class="fa fa-envelope"></i>
			</span>
			<input id="email" class="form-control" placeholder="email" name="email">
		</div>
		<div class="input-group">
			<span class="input-group-addon min-width__40px">
				<i class="fa fa-link"></i>
			</span>
			<input id="url" class="form-control" placeholder="website" name="site">
		</div>
		<div class="form-group">
			<textarea class="form-control" placeholder="Сообщение" name="comment" id="comment"></textarea>
		</div>
		<div class="form-group">
			<div class="b-form-check">
				<input class="form-check-input" type="checkbox" id="privacyCheck">
				<label class="form-check-label" for="privacyCheck">Я соглашаюсь с обработкой моих персональных данных</label>
			</div>
		</div>
		<button class="btn btn-success">Отправить</button>
	</form>
</div>--}}
<ol class="trackbacklist"></ol>
<div id="respond">
	<div class="b-header3">
		<h3 id="reply-title" class="b-h3">Leave a<span>Reply</span>
			<small>
				<a id="cancel-comment-reply-link" rel="nofollow" href="#respond" style="display:none;">Cancel reply</a>
			</small>
		</h3>
	</div>
	<form id="commentform" class="b-feedback m-b__15px" action="{{route('comment.store')}}" method="post">
		{{csrf_field()}}
		<input id="comment_post_ID" name="article_id" type="hidden" value="{{$article->id}}" />
		<input id="comment_parent" name="parent_id" type="hidden" value="0" />
		@if(!Auth::check())
			<div class="input-group">
				<p class="comment-form-author">
					<input class="form-control" id="name" name="name" type="text" value="" size="30" placeholder="Имя" aria-required="true">
				</p>
			</div>
			<div class="input-group">
				<p class="comment-form-email">
					<input class="form-control" id="email" name="email" type="text" value="" size="30" aria-required="true" placeholder="Email">
				</p>
			</div>
			<div class="input-group">
				<p class="comment-form-url">
					<input class="form-control" id="site" name="site" type="text" value="" size="30" placeholder="Website">
				</p>
			</div>
		@endif
		<div class="form-group">
			<p class="comment-form-comment">
				<textarea class="form-control" id="comment" name="text" cols="45" rows="8" placeholder="Message"></textarea>
			</p>
		</div>
		<div class="clear"></div>
		<p class="form-submit">
			<input class="btn btn-success" id="submit" type="submit" value="Post Comment">
		</p>
	</form>
</div>

app/resources/views/bootstrap4/comments.blade.php
{{-- #72 --}}
@foreach($comments as $comment)
	<li id="li-comment-{{ $comment->id }}" class="comment even {{ ($comment->user_id == $article->user_id) ?  'bypostauthor odd' : ''}}">
		<div id="comment-{{ $comment->id }}" class="comment-container">
			<div class="comment-author vcard">
				<img class="avatar" alt="" src="{{asset(env('THEME'))}}/img/no-avatar.png">
				<p>{{$comment->name}}</p>
			</div>
			<div class="comment-meta commentmetadata">
				<div class="intro">
					<div class="commentDate">
						<a href="#comment-{{ $comment->id }}">{{ is_object($comment->created_at) ? $comment->created_at->format('F d, Y \a\t H:i') : ''}}</a>
						@if($comment->parent_id && $comment->parent_id>0)
							в ответ на <a href="#comment-{{$comment->parent_id}}"> комментарий</a>
						@endif
					</div>
					<div class="commentNumber">#</div>
				</div>
				<div class="comment-body">
					{{$comment->text}}
				</div>
				<div class="reply group">
					<a class="comment-reply-link" href="#respond" onclick="return addComment.moveForm(&quot;comment-{{$comment->id}}&quot;, &quot;{{$comment->id}}&quot;, &quot;respond&quot;, &quot;{{$comment->article_id}}&quot;)">Reply</a>
				</div>
			</div>
		</div>
		@if(isset($articleGroup[$comment->id]))
			<ul class="children">
				@include(env('THEME').'.comments',['comments' => $articleGroup[$comment->id]])
			</ul>
		@endif
	</li>
@endforeach

app/resources/views/bootstrap4/contacts.blade.php
{{-- в данном шаблоне мы переопределяем все секции --}}
@extends(env('THEME').'.layouts.site')

@section('email')
	{!! $email !!}
@endsection

@section('address')
	{!! $address !!}
@endsection

@section('phone')
	{!! $phone !!}
@endsection

@section('copyright')
	{!! $copyright !!}
@endsection

@section('navbar')
	{!! $navbar !!}
@endsection

@section('contacts_content')
	{!! $contacts_content !!}
@endsection

app/resources/views/bootstrap4/copyrightBlock.blade.php
@if($copyright)
    <div class="b-copyright">
        {!! $copyright->content !!}
    </div>
@endif

app/resources/views/bootstrap4/email.blade.php
<h1>{{$data['text']}}</h1>

app/resources/views/bootstrap4/index.blade.php
{{-- в данном шаблоне мы переопределяем все секции --}}
@extends(env('THEME').'.layouts.site')

@section('email')
	{!! $email !!}
@endsection

@section('address')
	{!! $address !!}
@endsection

@section('phone')
	{!! $phone !!}
@endsection

@section('copyright')
	{!! $copyright !!}
@endsection

@section('navbar')
	{!! $navbar !!}
@endsection

@section('slider')
	{!! $slider !!}
@endsection

@section('advantages_block')
	{!! $advantages !!}
@endsection

@section('bar')
	{!! $rightBar !!}
@endsection

@section('portfolio_block')
	{!! $portfolio !!}
@endsection

app/resources/views/bootstrap4/indexBar.blade.php
@if($sidemenu)
	@include(env('THEME').'.sideMenu',['sidemenu' => $sidemenu])
@endif

@if($banners)
	@include(env('THEME').'.banners',['banners' => $banners])
@endif

@if($articles)
	<div class="b-side">
		<div class="b-side__inner">
			<div class="b-side__name">{{trans('ru.articles_block')}}</div>
			<div class="b-side__items">
				@foreach($articles as $article)
					<div class="b-side__item">
						<div class="b-side-item__icon">
							<a href="#">
								<img class="img-responsive" src="{{asset(env('THEME'))}}/img/{{ ($article->img) ? $article->img->path : 'no-img-small.png' }}">
							</a>
						</div>
						<div class="b-side-item__text">
							<div class="b-side-item__name"><a href="{{route('articles.show',['alias' => $article->alias])}}">{{$article->title}}</a></div>
							<div class="b-side-item__date"><span>{{$article->created_at->format('d.m.y')}}</span></div>
						</div>
					</div>
				@endforeach
			</div><a class="b-btn-more" href="#">More</a>
		</div>
	</div>
@endif

@if($slogan)
	<div class="b-side-text">
		{!! $slogan->content !!}
	</div>
@endif

app/resources/views/bootstrap4/navbar.blade.php
@if($menu)
	<div class="navbar-collapse collapse navbar-collapse--background">
		<div class="container">
			<ul class="nav navbar-nav">
				{{-- вызываем и передаем в шаблон только родительские пункты меню --}}
				@include(env('THEME').'.topMenuItems',['items' => $menu->roots()])
			</ul>
			<form class="navbar-form navbar-right">
				<div class="g-d-flex">
					<input class="form-control m-r__5px" placeholder="Поиск">
					<button class="btn btn-success">Найти</button>
				</div>
			</form>
		</div>
	</div>
@endif

app/resources/views/bootstrap4/sideMenuItems.blade.php
@foreach($items as $item)
	{{-- аккуратнее с кавычками, из-за них могут быть баги --}}
	<a class="list-group-item{{ ($item->hasChildren()) ? ' item-parent collapsed' : '' }}{{ (URL::current() == $item->url()) ? ' active' : '' }}" href="{{ ($item->hasChildren()) ? '#collapse'.$item->id : '' }}"{{ ($item->hasChildren()) ? ' data-toggle=collapse' : '' }}>{{$item->title}}</a>
	@if($item->hasChildren())
		<div class="panel-collapse collapse {{ (URL::current() == $item->url()) ? 'in' : '' }}" id="collapse{{$item->id}}">
			<div class="list-group-inner">
				@include(env('THEME').'.sideMenuChildrenItems',['items' => $item->children()])
			</div>
		</div>
	@endif
@endforeach

app/resources/views/bootstrap4/slider.blade.php
@setvalue($var,7)
@if(count($slider)>0)
    <div class="carousel slide" id="myCarousel" data-ride="carousel">
        <ol class="carousel-indicators hidden-xs">
            @for ($i=0; $i < count($slider); $i++)
                <li class="{{ ($i==0) ? 'active' : '' }}" data-target="#myCarousel" data-slide-to="{{ $i }}"></li>
            @endfor
        </ol>
        <div class="carousel-inner">
            @foreach($slider as $i => $slide)
                <div class="item {{ ($i==0) ? 'active' : '' }}">
                    <img src="{{asset(env('THEME'))}}/img/{{ ($slide->img) ? $slide->img : 'slide.png' }}" alt="" style="width:100%;">
                    <div class="container">
                        <div class="carousel-caption">
                            <h1 class="hidden-xxs">{{$slide->title}}</h1>
                            <p>{{$slide->desc}}</p>
                            <p><a class="btn btn-success" href="{{$slide->link}}">More</a></p>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span><span class="sr-only">Prev</span></a><a class="right carousel-control" href="#myCarousel" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span><span class="sr-only">Next</span></a>
    </div>
@endif